version: '3.4'
services:
  scrap_service:
        build: .
        container_name: "flight_scrap"
        user: "${UID}:${GID}"
        depends_on:
          - mongodb_service
        networks:
          - scrappy
        volumes:
          - scrapy_volume:/home/scrapy/backup

  mongodb_service:
        image: 'mongo:3.4.1'
        command: "--smallfiles"
        ports:
          - '27017:27017'
        networks:
          - scrappy

volumes:
  scrapy_volume:

networks:
  scrappy:
    driver: bridge
