version: '3.4'
services:
  scrap_service:
        build: .
        container_name: "flight_scrap"
        depends_on:
          - mongodb_service
        networks:
          - flight_scrappy
        volumes:
          - flight_scrapy_volume:/home/scrapy/backup

  mongodb_service:
        image: 'mongo:3.4.1'
        command: "--smallfiles"
        ports:
          - '27017:27017'
        networks:
          - flight_scrappy

volumes:
  flight_scrapy_volume:

networks:
  flight_scrappy:
    driver: bridge
